# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nomina_helper_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.mensaje_progreso = QtGui.QLabel(self.tab)
        self.mensaje_progreso.setObjectName(_fromUtf8("mensaje_progreso"))
        self.horizontalLayout_5.addWidget(self.mensaje_progreso)
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.barra_progreso = QtGui.QProgressBar(self.tab)
        self.barra_progreso.setProperty("value", 24)
        self.barra_progreso.setObjectName(_fromUtf8("barra_progreso"))
        self.horizontalLayout_5.addWidget(self.barra_progreso)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ruta_archivo_nomina = QtGui.QLineEdit(self.tab)
        self.ruta_archivo_nomina.setObjectName(_fromUtf8("ruta_archivo_nomina"))
        self.horizontalLayout_2.addWidget(self.ruta_archivo_nomina)
        self.boton_cargar_archivo = QtGui.QPushButton(self.tab)
        self.boton_cargar_archivo.setObjectName(_fromUtf8("boton_cargar_archivo"))
        self.horizontalLayout_2.addWidget(self.boton_cargar_archivo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabla_empleados = QtGui.QTableWidget(self.tab)
        self.tabla_empleados.setObjectName(_fromUtf8("tabla_empleados"))
        self.tabla_empleados.setColumnCount(0)
        self.tabla_empleados.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tabla_empleados)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.boton_calcular_nomina = QtGui.QPushButton(self.tab)
        self.boton_calcular_nomina.setEnabled(False)
        self.boton_calcular_nomina.setObjectName(_fromUtf8("boton_calcular_nomina"))
        self.horizontalLayout_3.addWidget(self.boton_calcular_nomina)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.tabla_apropiaciones = QtGui.QTableWidget(self.tab)
        self.tabla_apropiaciones.setEnabled(False)
        self.tabla_apropiaciones.setObjectName(_fromUtf8("tabla_apropiaciones"))
        self.tabla_apropiaciones.setColumnCount(0)
        self.tabla_apropiaciones.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tabla_apropiaciones)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.tabla_deducciones = QtGui.QTableWidget(self.tab)
        self.tabla_deducciones.setEnabled(False)
        self.tabla_deducciones.setObjectName(_fromUtf8("tabla_deducciones"))
        self.tabla_deducciones.setColumnCount(0)
        self.tabla_deducciones.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tabla_deducciones)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.tabla_liquidacion = QtGui.QTableWidget(self.tab)
        self.tabla_liquidacion.setEnabled(False)
        self.tabla_liquidacion.setObjectName(_fromUtf8("tabla_liquidacion"))
        self.tabla_liquidacion.setColumnCount(0)
        self.tabla_liquidacion.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tabla_liquidacion)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.boton_guardar_liquidacion = QtGui.QPushButton(self.tab)
        self.boton_guardar_liquidacion.setEnabled(False)
        self.boton_guardar_liquidacion.setObjectName(_fromUtf8("boton_guardar_liquidacion"))
        self.horizontalLayout_6.addWidget(self.boton_guardar_liquidacion)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.nombre_archivo_errores = QtGui.QLineEdit(self.tab_2)
        self.nombre_archivo_errores.setObjectName(_fromUtf8("nombre_archivo_errores"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nombre_archivo_errores)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.nombre_archivo_registro = QtGui.QLineEdit(self.tab_2)
        self.nombre_archivo_registro.setObjectName(_fromUtf8("nombre_archivo_registro"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nombre_archivo_registro)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_14)
        self.nombre_archivo_liquidacion = QtGui.QLineEdit(self.tab_2)
        self.nombre_archivo_liquidacion.setObjectName(_fromUtf8("nombre_archivo_liquidacion"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nombre_archivo_liquidacion)
        self.numero_minimo_lineas = QtGui.QLineEdit(self.tab_2)
        self.numero_minimo_lineas.setObjectName(_fromUtf8("numero_minimo_lineas"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.numero_minimo_lineas)
        self.smlv = QtGui.QLineEdit(self.tab_2)
        self.smlv.setObjectName(_fromUtf8("smlv"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.smlv)
        self.auxilio_transporte = QtGui.QLineEdit(self.tab_2)
        self.auxilio_transporte.setObjectName(_fromUtf8("auxilio_transporte"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.auxilio_transporte)
        self.tope_auxilio_transporte = QtGui.QLineEdit(self.tab_2)
        self.tope_auxilio_transporte.setEnabled(True)
        self.tope_auxilio_transporte.setReadOnly(True)
        self.tope_auxilio_transporte.setObjectName(_fromUtf8("tope_auxilio_transporte"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.tope_auxilio_transporte)
        self.tope_fondo_solidaridad = QtGui.QLineEdit(self.tab_2)
        self.tope_fondo_solidaridad.setReadOnly(True)
        self.tope_fondo_solidaridad.setObjectName(_fromUtf8("tope_fondo_solidaridad"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.tope_fondo_solidaridad)
        self.porcentaje_fondo_solidaridad = QtGui.QLineEdit(self.tab_2)
        self.porcentaje_fondo_solidaridad.setObjectName(_fromUtf8("porcentaje_fondo_solidaridad"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.porcentaje_fondo_solidaridad)
        self.porcentaje_arl = QtGui.QLineEdit(self.tab_2)
        self.porcentaje_arl.setObjectName(_fromUtf8("porcentaje_arl"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.porcentaje_arl)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.verticalLayout_7.addLayout(self.formLayout)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.aplicar_cambios = QtGui.QPushButton(self.tab_2)
        self.aplicar_cambios.setObjectName(_fromUtf8("aplicar_cambios"))
        self.horizontalLayout_8.addWidget(self.aplicar_cambios)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.cargar_valores_defecto = QtGui.QPushButton(self.tab_2)
        self.cargar_valores_defecto.setObjectName(_fromUtf8("cargar_valores_defecto"))
        self.horizontalLayout_8.addWidget(self.cargar_valores_defecto)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NominaHelper", None))
        self.mensaje_progreso.setText(_translate("MainWindow", "Mensaje de estado ...", None))
        self.boton_cargar_archivo.setText(_translate("MainWindow", "Cargar Archivo", None))
        self.boton_calcular_nomina.setText(_translate("MainWindow", "Calcular Nomina", None))
        self.label_2.setText(_translate("MainWindow", "Apropiaciones", None))
        self.label_3.setText(_translate("MainWindow", "Deducciones", None))
        self.label_4.setText(_translate("MainWindow", "Liquidación", None))
        self.boton_guardar_liquidacion.setText(_translate("MainWindow", "Guardar Liquidacion", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Principal", None))
        self.label_5.setText(_translate("MainWindow", "Nombre archivo errores", None))
        self.label_6.setText(_translate("MainWindow", "Nombre archivo registro", None))
        self.label_7.setText(_translate("MainWindow", "Nombre archivo liquidación", None))
        self.label_8.setText(_translate("MainWindow", "Numero mínimo de lineas", None))
        self.label_10.setText(_translate("MainWindow", "Auxilio de Transporte", None))
        self.label_11.setText(_translate("MainWindow", "Tope Auxilio de Transporte", None))
        self.label_12.setText(_translate("MainWindow", "Tope Fondo Solidaridad", None))
        self.label_13.setText(_translate("MainWindow", "Porcentaje Fondo Solidaridad", None))
        self.label_14.setText(_translate("MainWindow", "Porcentaje ARL", None))
        self.label_9.setText(_translate("MainWindow", "SMLV", None))
        self.aplicar_cambios.setText(_translate("MainWindow", "Aplicar Cambios", None))
        self.cargar_valores_defecto.setText(_translate("MainWindow", "Valores por Defecto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Configuración", None))

